import { useEffect, useState } from "react";
import { ArrowRight, Send } from "lucide-react";
import { errorMessage } from "../../shared/error";
import type { Run } from "../runs";
import { deliverContextShare, previewContextShare } from "./api";
import type { ContextShare, SharePreview } from "./model";

export function ContextSharePanel({ runs }: { runs: Run[] }) {
  const [sourceRunId, setSourceRunId] = useState(runs[0]?.id ?? "");
  const [targetRunId, setTargetRunId] = useState(runs[1]?.id ?? "");
  const [kind, setKind] = useState<"file" | "output_excerpt" | "summary">("summary");
  const [reference, setReference] = useState("");
  const [summary, setSummary] = useState("");
  const [preview, setPreview] = useState<SharePreview | null>(null);
  const [result, setResult] = useState<ContextShare | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { if (sourceRunId === targetRunId) setTargetRunId(runs.find((run) => run.id !== sourceRunId)?.id ?? ""); setPreview(null); }, [sourceRunId, targetRunId, runs]);
  if (runs.length < 2) return null;
  const input = { sourceRunId: kind === "summary" && !sourceRunId ? null : sourceRunId, targetRunId, kind, contentReference: reference || null, summary };
  async function makePreview() { setError(""); setResult(null); try { setPreview(await previewContextShare(input)); } catch (reason) { setError(errorMessage(reason)); } }
  async function deliver() { if (!preview) return; setError(""); try { setResult(await deliverContextShare({ sourceRunId: input.sourceRunId, targetRunId, kind, contentReference: input.contentReference, content: preview.content, previewSha256: preview.sha256 })); } catch (reason) { setError(errorMessage(reason)); } }
  return <section className="mt-8" aria-label="Share context"><h3 className="text-sm font-medium text-primary">Share context between agents</h3><p className="mt-1 text-xs text-tertiary">Preview exactly what will be typed into a live target terminal.</p><div className="mt-3 grid gap-3 bg-chrome p-3 lg:grid-cols-[1fr_auto_1fr_1fr]"><label className="grid gap-1 text-[11px] text-secondary">Source<select className="rounded border border-line bg-app p-2 text-xs" onChange={(event) => setSourceRunId(event.target.value)} value={sourceRunId}>{runs.map((run) => <option key={run.id} value={run.id}>{run.providerName} · {run.status}</option>)}</select></label><ArrowRight aria-hidden="true" className="mt-7 hidden text-tertiary lg:block" size={14} /><label className="grid gap-1 text-[11px] text-secondary">Target<select className="rounded border border-line bg-app p-2 text-xs" onChange={(event) => { setTargetRunId(event.target.value); setPreview(null); }} value={targetRunId}>{runs.filter((run) => run.id !== sourceRunId).map((run) => <option disabled={!['preparing','running','waiting'].includes(run.status)} key={run.id} value={run.id}>{run.providerName} · {run.status}</option>)}</select></label><label className="grid gap-1 text-[11px] text-secondary">Kind<select className="rounded border border-line bg-app p-2 text-xs" onChange={(event) => { setKind(event.target.value as typeof kind); setPreview(null); }} value={kind}><option value="summary">Summary</option><option value="file">File</option><option value="output_excerpt">Recent output</option></select></label></div>{kind === "file" && <label className="mt-3 grid gap-1 text-[11px] text-secondary">Relative file path<input className="rounded border border-line bg-app p-2 text-xs" onChange={(event) => { setReference(event.target.value); setPreview(null); }} placeholder="src/feature/mod.rs" value={reference} /></label>}{kind === "summary" && <label className="mt-3 grid gap-1 text-[11px] text-secondary">Summary<textarea className="rounded border border-line bg-app p-2 text-xs" onChange={(event) => { setSummary(event.target.value); setPreview(null); }} rows={3} value={summary} /></label>}<div className="mt-3 flex items-center gap-2"><button className="button-secondary" onClick={makePreview} type="button">Preview</button>{preview && <><span className="font-mono text-[10px] text-tertiary">{preview.sizeBytes.toLocaleString()} bytes</span><button className="button-primary ml-auto" onClick={deliver} type="button"><Send size={13} />Deliver</button></>}</div>{preview && <pre className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap border-t border-line pt-3 font-mono text-[11px] leading-5 text-secondary">{preview.content}</pre>}{error && <p className="error-banner" role="alert">{error}</p>}{result && <p className={result.deliveryStatus === "delivered" ? "mt-3 text-xs text-complete" : "mt-3 text-xs text-failed"}>{result.deliveryStatus === "delivered" ? "Context delivered and recorded." : result.deliveryError}</p>}</section>;
}
